### ISSUE TITLE
wind-roses.qmd: @fig-pollRoseComp doesn't make sense

### ISSUE THREAD

**Issue by vvxin** [davidcarslaw/openair-book#4]
Dear David, Dear Jack,

I am translating this book as a side project ('zh_CN' branch of my fork), and now working on Chapter 5.  I find the example in 5.2 confusing.

```
mydata <- mutate(mydata,
  ws2 = ws + 2 * rnorm(nrow(mydata)) + 1,
  wd2 = wd + 30 * rnorm(nrow(mydata)) + 30
) 
```

This code rotates wd 30 degrees clockwise, and the  [@fig-pollRoseComp](https://bookdown.org/david_carslaw/openair/wind-roses.html#fig-pollRoseComp) shows positive wd bias ONLY at 30 degree(NNE).   It doesn't make any sense.  For me, the first and natural response to this figure is wow! what's happened in the northeast of site2?   But it's not the case.  The case is you rotate wd from all directions, so all directions should have bias positive or negative. 

If I understand this right, please reconsider the example or maybe `pollutionRose` itself.

Thanks
Wang Xin

**Comment by jack-davison** [comment]
Hi Xin,

I've opened an issue for `{openair}` relating to this, because you are right that it is a bit confusing! Hopefully we can update the `pollutionRose()` function to properly label the axes to be less misleading.

Thanks,
Jack

**Comment by jack-davison** [comment]
Hi again Xin,

I've just pushed an update to the development version of `{openair}` that labels the axes more appropriately.

<img src="https://user-images.githubusercontent.com/45171616/224545184-8eabe868-1c55-4d4b-9f35-5df824222cc9.png" alt="drawing" width="400"/>

The openair book will be updated at the next available moment.

Thanks,
Jack

**Comment by vvxin** [comment]
Cool, Thanks, Jack.

![image](https://user-images.githubusercontent.com/15047983/224888290-91719ed2-8c20-48d1-a3ee-3d0c11fb25f6.png)
But I plot with real data and I still think this visualization is not practically informative when comparing two met datasets.  The reasons I could think of at the moment are:
1. It plots the **offset** which means the distance between two wind directions. But we (maybe just me) don't think that way.  The east wind is the east wind. The northwest wind is the northwest wind.  The east wind in wd2 doesn't come from the northwest wind in wd1.  The + or - 120 degrees between them have nothing to do with pollution analysis.
2. Exclusively plotting the offset means it lost the whole information from the original wind profiles.  If you rotate two wind data with a same angle, you will get the same offset plot.  So I can't see any useful information only from the wd offset plot.   
3. I may be wrong about this but I think positive(red) and negative(blue) wind speeds are the same thing,  there's no need to stack them together.  The useful information here is the "mean ws" (should be "mean ws bias"?) in the corner.

It's challenging indeed to plot 2 wind datasets on 1 polar system and compare them.  I'll think about it also.  Thanks again.
