### ISSUE TITLE
Broken link correction

### ISSUE THREAD

**Issue by BlaiseKelly** [davidcarslaw/openair-book#9]
Broken link at:
https://bookdown.org/david_carslaw/openair/sections/model-evaluation/taylor-diagram.html

Link to Taylor primer was
https://pcmdi.llnl.gov/about/staff/Taylor/CV/Taylor_diagram_primer.pdf
Is now
https://pcmdi.llnl.gov/staff/taylor/CV/Taylor_diagram_primer.pdf

**Comment by jack-davison** [comment]
Thanks! Fixed it in the qmd file - will carry over next time the openair book is compiled.
